// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutohideController from "./autohide_controller.js"
application.register("autohide", AutohideController)

import FormModalController from "./form_modal_controller.js"
application.register("form-modal", FormModalController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)
