// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CocurriculumFormController from "./cocurriculum_form_controller.js"
application.register("cocurriculum-form", CocurriculumFormController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)
